
async function dbChecker(db){
    /* ----------------------------- Todo DB Checker ---------------------------- */
    try{
        var date = await db.query("SELECT * FROM public.todo");
        console.log("ToDo DB exists nothing was created");
    }catch(error){
        console.error("Table does not exist creating a new TODO table and will fill with dummy data");
        await db.query("CREATE TABLE todo( id bigint GENERATED BY DEFAULT AS IDENTITY, item text, completed BOOLEAN DEFAULT FALSE)")
        //Dummy Info
        var dummy = [["To Do 1", false],["To Do 2", false],["To Do 3", false], ["To Do 4", true]];
        
        for(let i=0; i < dummy.length; i++){
            db.query("INSERT INTO public.todo ( item, completed) VALUES ($1, $2)", [ dummy[i][0], dummy[i][1]]);
        }
        console.log("ToDo Database Succesfully Created")
    }
    
    
}

export default dbChecker; 