
async function dbChecker(db){
    /* ----------------------------- Todo DB Checker ---------------------------- */
    try{
        var date = await db.query("SELECT * FROM public.todo");
        console.log("ToDo DB exists nothing was created");
    }catch(error){
        console.error("Table does not exist creating a new TODO table and will fill with dummy data");
        await db.query("CREATE TABLE todo( id bigint GENERATED BY DEFAULT AS IDENTITY, item text, completed BOOLEAN DEFAULT FALSE)")
        //Dummy Info
        var dummy = [["To Do 1", false],["To Do 2", false],["To Do 3", false], ["To Do 4", true]];
        
        for(let i=0; i < dummy.length; i++){
            db.query("INSERT INTO public.todo ( item, completed) VALUES ($1, $2)", [ dummy[i][0], dummy[i][1]]);
        }
        console.log("ToDo Database Succesfully Created")
    }
    /* ----------------------------- Travel DB Checker ---------------------------- */

    try{
        var travel = await db.query("SELECT * FROM public.travel");
        console.log("Travel DB does not exist nothing was created");
    }catch(error){
        console.error("Travel Table Does not exist. Creating a new Travel Table and Filling with Dummy Data")
        await db.query("CREATE TABLE travel( id bigint GENERATED BY DEFAULT AS IDENTITY, tripname text)")
        var dummy = [["Thailand 2/5/25"], ["Trip 2"]];

        for(let i=0; i < dummy.length; i++){
            db.query("INSERT INTO public.travel ( tripname) VALUES ($1)", [dummy[i][0]]);
        }
        console.log("Travel Database Succesfully Created")
    }
    
}

export default dbChecker; 